version: "3"
services: 
  app:
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
  
  db:
    image: postgres
    volumes: 
      - ./.docker/database:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root

