version: '3'
services:
  app:
    image: node:alpine
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: yarn start:dev

  database:
    image: redis:alpine
    ports:
      - 6379:6379
